name: Test and Lint

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: NovaPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '18'
      pkg_manager: 'npm'
      install: 'npm install'
      name: 'test'
      command_one: 'npm run startLocalHardhat & npm run coverage'
      command_one_name: 'Run Tests'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
      